INSERT IGNORE INTO quadros(idCategoria, nome, descricao, preco, imagemDiretorio)
VALUES (1,
        'Alone Street Lamp',
        'Sozinho apenas sozinho, iluminando tudo mas sozinho.',
        50.00,
        'images/Analogia/Alone_street_lamp.jpg'),

        (1,
         'Christmas Day',
         'O natal chegou, época de encontrar pessoas que você se importa com',
        70.00,
         'images/Analogia/Christmas_day.jpg'),

        (1,
         'Little Autumn Rain',
         'Chuva no outono, com a brisa fria da estação',
         45.00,
         'images/Analogia/Little_Autumn_Rain.jpg'),

        (1,
         'Snow and Rain',
         'Dois estados da água juntos ao mesmo tempo.',
         35.00,
         'images/Analogia/Snow_and_Rain.jpg'),

        (1,
         'Thanksgiving',
         'Data comemorativa com feriado apenas nos Estados Unidos',
         40.00,
         'images/Analogia/Thanksgiving.jpg'),

        (1,
         'Valentines Day in Winter',
         'Anteciparam o feriado para o inverno',
         60.00,
         'images/Analogia/Valentines_day_in_winter.jpg'),

        (2,
         'Album Rocket',
         'Capa de album de rock com rockets',
         70.00,
         'images/Cubismo/Album_rocket.jpg'),

        (2,
         'Bugged Houses',
         'A imagem veio bugada',
         40.00,
         'images/Cubismo/Bugged_houses.jpg'),

        (2,
         'Cubic Temple',
         'Antigamente um deus era cultuado ai, agora não mais.',
         60.00,
         'images/Cubismo/Cubic_temple.jpg'),

        (2,
         'Goat',
         'Ele está sério olhando para você, ele pode te dar conselhos sobre a vida',
         45.00,
         'images/Cubismo/Goat.jpg'),

        (2,
         'Horizon Pink',
         'TEMPLATE',
         40.00,
         'images/Cubismo/Horizon_pink.jpg'),

        (2,
         'Looking at the horizon',
         'TEMPLATE',
         45.00,
         'images/Cubismo/Looking_at_the_horizon.jpg'),

        (3,
         'Abraham',
         'TEMPLATE',
         50.00,
         'images/Fotorrealista/Abraham.jpg'),

       (3,
        'King Mercury',
        'TEMPLATE',
        30.00,
        'images/Fotorrealista/King_mercury.jpg'),

       (3,
        'Michael Jackson',
        'TEMPLATE',
        30.00,
        'images/Fotorrealista/Michael_jackson.jpg'),

        (3,
         'Santa Claus',
         'TEMPLATE',
         40.00,
         'images/Fotorrealista/Santa_claus.jpg'),

        (3,
         'Slash',
         'TEMPLATE',
         50.00,
         'images/Fotorrealista/Slash.jpg'),

        (3,
         'Visions of war',
         'TEMPLATE',
         30.00,
         'images/Fotorrealista/Vision_of_war.jpg'),



        (4,
         'Brilliant Sky',
         'Um homem mostrando seu olhar sem brilho depois da guerra',
         79.99,
         'images/Grunge/Brilliant_sky.jpg'),

        (4,
         'Lighting City',
         'Vamos dar uma volta pela cidade e ver como ela fica brilhante de noite',
         65.00,
         'images/Grunge/Lighting_city.jpg'),

        (4,
         'Lost and Forgotten',
         'Me perdi e sinceramente esqueci o caminho de casa, acho que não volto tão cedo.',
         40.00,
         'images/Grunge/Lost_and_forgotten.jpg'),

        (4,
         'Meteor Shower',
         'Uma chuva de asteróides no inverno',
         35.00,
         'images/Grunge/Meteor_shower.jpg'),

        (4,
         'Way for Home',
         'Andar por aqui é muito bom, o caminho de casa sempre é fácil de achar',
         70.00,
         'images/Grunge/Way_for_home.jpg'),

        (4,
         'Way of the River',
         'Esse é o caminho que o rio acha para passar pela cidade',
         50.00,
         'images/Grunge/Way_of_the_river.jpg'),

        (5,
         'Giant Lampshade',
         'TEMPLATE',
         60.00,
         'images/Surrealismo/Giant_lampshade.jpg'),

        (5,
         'Horned Creature',
         'TEMPLATE',
         35.00,
         'images/Surrealismo/Horned_creature.jpg'),

        (5,
         'Light Up',
         'TEMPLATE',
         50.00,
         'images/Surrealismo/Light_up.jpg'),

        (5,
         'Robots are Here',
         'TEMPLATE',
         35.00,
         'images/Surrealismo/Robots_are_here.jpg'),

        (5,
         'Skyblock',
         'TEMPLATE',
         50.00 ,
         'images/Surrealismo/Skyblock.jpg'),

        (5,
         'Stop in the Time',
         'TEMPLATE',
         60.00,
         'images/Surrealismo/Stop_in_the_time.jpg'),

        (6,
         'Alley Sold',
         'TEMPLATE',
         50.00,
         'images/Variado/Alley_sold.jpg'),

        (6,
         'Camp of Flowers',
         'TEMPLATE',
         45.00,
         'images/Variado/Camp_of_flowers.jpg'),

        (6,
         'Conifers Florest',
         'TEMPLATE',
         35.00,
         'images/Variado/Conifers_florest.jpg'),

        (6,
         'Crow',
         'TEMPLATE',
         40.00,
         'images/Variado/Crow.jpg'),

        (6,
         'Elegant Goat',
         'TEMPLATE',
         50.00,
         'images/Variado/Elegant_goat.jpg'),

        (6,
         'Farm',
         'TEMPLATE',
         40.00,
         'images/Variado/Farm.jpg')


